[package]
name = "vexv5_serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
anyhow = "1.0.0"
crc = "2.1.0"
bitflags = "1.3.2"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"